### ISSUE TITLE
Raise heap memory

### ISSUE THREAD

**Issue by lazzarello** [kframework/viper-semantics#4]
Compiling lll-evm.k throws a Java exception

```
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at scala.util.Left$.apply(Either.scala:355)
	at org.kframework.parser.ChildrenMapping.doTheMapping(Transformer.scala:69)
	at org.kframework.parser.ChildrenMapping.mapChildrenWithClone(Transformer.scala:78)
	at org.kframework.parser.concrete2kore.disambiguation.TreeCleanerVisitor$TreeCleanerVisitor2.apply(TreeCleanerVisitor.java:69)
	at org.kframework.parser.TransformerWithErrors.apply(Transformer.scala:173)
	at org.kframework.parser.concrete2kore.disambiguation.TreeCleanerVisitor.apply(TreeCleanerVisitor.java:28)
	at org.kframework.parser.TransformerWithErrors.apply(Transformer.scala:182)
	at org.kframework.parser.TransformerWithErrors.apply(Transformer.scala:175)
	at org.kframework.parser.TransformerWithErrors.applyTerm(Transformer.scala:160)
	at org.kframework.parser.ChildrenMapping.$anonfun$mapChildrenStrict$1(Transformer.scala:30)
	at org.kframework.parser.ChildrenMapping$$Lambda$222/1807426335.apply(Unknown Source)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$Lambda$22/641853239.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.kframework.parser.ChildrenMapping.mapChildrenStrict(Transformer.scala:30)
	at org.kframework.parser.TransformerWithErrors.apply(Transformer.scala:188)
	at org.kframework.parser.concrete2kore.disambiguation.TreeCleanerVisitor.apply(TreeCleanerVisitor.java:49)
	at org.kframework.parser.TransformerWithErrors.apply(Transformer.scala:174)
	at org.kframework.parser.TransformerWithErrors.applyTerm(Transformer.scala:160)
	at org.kframework.parser.ChildrenMapping.$anonfun$doTheMapping$1(Transformer.scala:57)
	at org.kframework.parser.ChildrenMapping$$Lambda$221/106377256.apply(Unknown Source)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$Lambda$22/641853239.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
```

I would like to raise the heap memory. I'm familiar with the syntax `-Xmx` but the `kompile` executable does not take Java options.

**Comment by lazzarello** [comment]
I found the `JAVA_OPTS` environment variable and set it to

`JAVA_OPTS="-Xmx2g"`

The resident memory of the java process doesn't go higher than 1.1g but I continue to get the GC overhead execption.

**Comment by denis-bogdanas** [comment]
Can you give more details please? What commit of K are you using and what command are you running?
